### PR TITLE
Switch to node-gitter

### PR DESCRIPTION
**Pull request by spencerwahl**
[Review on Reviewable](https://reviewable.io/reviews/muffin-crusaders/hubot-scrumminator/5)

### CODE REVIEW

**Comment by AleksueiR** [comment]
Reviewed 1 of 2 files at r1.
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

<sup>**[src/model/scrum.coffee, line 27 \[r1\]](https://reviewable.io:443/reviews/muffin-crusaders/hubot-scrumminator/5#-K06yVfOut_sxL2PHt8s)** ([raw file](https://github.com/muffin-crusaders/hubot-scrumminator/blob/afe2d004ae892e93da8d0d6c09f2c6bb9c6aea3d/src/model/scrum.coffee#L27)):</sup>
You don't need to match room ids; there is a simpler way to listen to chat messages:
```js
gitter.rooms.join(roomName).then((room) ->
            events = room.streaming().chatMessages();

            console.log('room id', room.name, room.id)

            events.on('chatMessages', (message) ->
                console.log('A message was ' + message.operation);
                console.log('Text: ', message.model.text);
            )
        )
```
`roomName` is just room's name, like `fgvp-pvgf/fgvp-pvgf`.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/muffin-crusaders/hubot-scrumminator/5)

**Comment by alyec** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/muffin-crusaders/hubot-scrumminator/5)

**Comment by AleksueiR** [comment]
Reviewed 1 of 1 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/muffin-crusaders/hubot-scrumminator/5)

**Comment by alyec** [comment]
Reviewed 1 of 1 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/muffin-crusaders/hubot-scrumminator/5)

**Pull request merged**
