### PR TITLE
ITS HERE

### PR DESCRIPTION
**Pull request by spencerwahl**
[Review on Reviewable](https://reviewable.io/reviews/muffin-crusaders/hubot-scrumminator/4)

### CODE REVIEW

**Comment by AleksueiR** [comment]
How did you solve the brain loading issue? You made the local change, but is it committed anywhere?


---

Reviewed 1 of 3 files at r1, 1 of 1 files at r2.
Review status: 2 of 4 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

<sup>**[src/model/scrum.coffee, line 134 \[r3\]](https://reviewable.io:443/reviews/muffin-crusaders/hubot-scrumminator/4#-K02LYAlL092jNvE6U-V)** ([raw file](https://github.com/muffin-crusaders/hubot-scrumminator/blob/62243e45ecb57c735a4bcafa9d67ac9818436a08/src/model/scrum.coffee#L134)):</sup>
Need to match Mark's style as well: 
```
1- meetings, more tutorial, lecture and testing
2- lecture and testing
3- No blocks
4- Nothing to add to the sprint
5- Nothing new to report
```


---

<sup>**[src/model/scrum.coffee, line 150 \[r3\]](https://reviewable.io:443/reviews/muffin-crusaders/hubot-scrumminator/4#-K02Lt0v1uFUCCgWe_9Q)** ([raw file](https://github.com/muffin-crusaders/hubot-scrumminator/blob/62243e45ecb57c735a4bcafa9d67ac9818436a08/src/model/scrum.coffee#L150)):</sup>
This will end the scrum way to soon. Shouldn't it be 15 minutes instead?


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/muffin-crusaders/hubot-scrumminator/4)

**Comment by AleksueiR** [comment]
Don't forget to add `Closes #2` to the last commit.


---

Review status: 2 of 4 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/muffin-crusaders/hubot-scrumminator/4)

**Comment by spencerwahl** [comment]
brain changes are on https://github.com/muffin-crusaders/hubot-azure-scripts


---

Review status: 2 of 4 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

<sup>**[src/model/scrum.coffee, line 134 \[r3\]](https://reviewable.io:443/reviews/muffin-crusaders/hubot-scrumminator/4#-K02LYAlL092jNvE6U-V)** ([raw file](https://github.com/muffin-crusaders/hubot-scrumminator/blob/62243e45ecb57c735a4bcafa9d67ac9818436a08/src/model/scrum.coffee#L134)):</sup>
good point


---

<sup>**[src/model/scrum.coffee, line 150 \[r3\]](https://reviewable.io:443/reviews/muffin-crusaders/hubot-scrumminator/4#-K02Lt0v1uFUCCgWe_9Q)** ([raw file](https://github.com/muffin-crusaders/hubot-scrumminator/blob/62243e45ecb57c735a4bcafa9d67ac9818436a08/src/model/scrum.coffee#L150)):</sup>
Yep, I got a little ahead of myself


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/muffin-crusaders/hubot-scrumminator/4)

**Comment by AleksueiR** [comment]
You need to add azure scrips to list of dependencies. Something like:
`"hubot-azure-scripts": "https://github.com/muffin-crusaders/hubot-azure-scripts#master"`


---

Review status: 2 of 4 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/muffin-crusaders/hubot-scrumminator/4)

**Comment by spencerwahl** [comment]
Don't merge yet, I forgot a couple small things


---

Review status: 2 of 4 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

<sup>**[src/model/scrum.coffee, line 134 \[r3\]](https://reviewable.io:443/reviews/muffin-crusaders/hubot-scrumminator/4#-K02LYAlL092jNvE6U-V)** ([raw file](https://github.com/muffin-crusaders/hubot-scrumminator/blob/62243e45ecb57c735a4bcafa9d67ac9818436a08/src/model/scrum.coffee#L134)):</sup>
Done, thanks


---

<sup>**[src/model/scrum.coffee, line 150 \[r3\]](https://reviewable.io:443/reviews/muffin-crusaders/hubot-scrumminator/4#-K02Lt0v1uFUCCgWe_9Q)** ([raw file](https://github.com/muffin-crusaders/hubot-scrumminator/blob/62243e45ecb57c735a4bcafa9d67ac9818436a08/src/model/scrum.coffee#L150)):</sup>
Done, thanks


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/muffin-crusaders/hubot-scrumminator/4)

**Comment by alyec** [comment]
Reviewed 1 of 1 files at r2, 1 of 2 files at r3, 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/muffin-crusaders/hubot-scrumminator/4)

**Comment by AleksueiR** [comment]
Could you, please, also add some comments? That would be great.


---

Reviewed 1 of 2 files at r3, 2 of 2 files at r4.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/muffin-crusaders/hubot-scrumminator/4)

**Comment by alyec** [comment]
But coffeescript reads so well on its own


---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/muffin-crusaders/hubot-scrumminator/4)

**Comment by AleksueiR** [comment]
Reviewed 2 of 2 files at r6.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/muffin-crusaders/hubot-scrumminator/4)

**Pull request merged**
